version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium_chrome
    shm_size: "2g"
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 10s
      retries: 5

  tests:
    build: .
    container_name: skillboost_ui_tests
    depends_on:
      selenium:
        condition: service_healthy
    working_dir: /app
    environment:
      CI: "true"
      SELENIUM_REMOTE_URL: http://selenium:4444/wd/hub
      ALLURE_RESULTS_PATH: /app/allure-results
    volumes:
      - ./allure-results:/app/allure-results
    command: >
      mvn clean test
      -Dselenium.remote=http://selenium:4444/wd/hub
      -Dallure.results.directory=/app/allure-results
